editAreaLoader.lang["hr"]={
newDocument: "Novi dokument",
searchButton: "Traži i izmijeni",
searchCommand: "Traži dalje / Otvori prozor za traženje",
search: "Traži",
replace: "Izmijeni",
replaceCommand: "Izmijeni / Otvori prozor za traženje",
findNext: "Traži dalje",
replaceAll: "Izmjeni sve",
regExp: "Regularni izrazi",
matchCase: "Bitna vel. slova",
notFound: "nije naðeno.",
occurrenceReplaced: "izmjenjenih.",
searchFieldEmpty: "Prazno polje za traženje!",
restartSearchAtBegin: "Došao do kraja. Poèeo od poèetka.",
movePopup: "Pomakni prozor",
fontSize: "--Velièina teksta--",
goToLine: "Odi na redak",
goToLine_prompt: "Odi na redak:",
undo: "Vrati natrag",
redo: "Napravi ponovo",
changeSmoothSelection: "Ukljuèi/iskljuèi neke moguænosti prikaza (pametniji prikaz, ali zagušeniji CPU)",
highlight: "Ukljuèi/iskljuèi bojanje sintakse",
resetHighlight: "Ponovi kolorizaciju (ako je nesinkronizirana s tekstom)",
wordWrap: "toggle word wrapping mode",
help: "O edit_area",
save: "Spremi",
load: "Uèitaj",
lineAbbr: "Ln",
charAbbr: "Zn",
position: "Pozicija",
total: "Ukupno",
closePopup: "Zatvori prozor",
shortcuts: "Kratice",
addTab: "Dodaj tabulaciju",
removeTab: "Makni tabulaciju",
aboutNotice: "Napomena: koloriziranje sintakse je samo za kratke kodove",
toggle: "Prebaci naèin ureðivanja",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Procesiram...",
fullscreen: "Cijeli prozor",
syntaxSelection: "--Syntax--",
closeTab: "Close file"
};
