editAreaLoader.lang["zh"]={
newDocument: "新建空白文档",
searchButton: "查找与替换",
searchCommand: "查找下一个 / 打开查找框",
search: "查找",
replace: "替换",
replaceCommand: "替换 / 打开查找框",
findNext: "查找下一个",
replaceAll: "全部替换",
regExp: "正则表达式",
matchCase: "匹配大小写",
notFound: "未找到.",
occurrenceReplaced: "处被替换.",
searchFieldEmpty: "查找框没有内容",
restartSearchAtBegin: "已到到文档末尾. 从头重新查找.",
movePopup: "移动查找对话框",
fontSize: "--字体大小--",
goToLine: "转到行",
goToLinePrompt: "转到行:",
undo: "恢复",
redo: "重做",
changeSmoothSelection: "启用/禁止一些显示特性(更好看但更耗费资源)",
highlight: "启用/禁止语法高亮",
resetHighlight: "重置语法高亮(当文本显示不同步时)",
wordWrap: "toggle word wrapping mode",
help: "关于",
save: "保存",
load: "加载",
lineAbbr: "行",
charAbbr: "字符",
position: "位置",
total: "总计",
closePopup: "关闭对话框",
shortcuts: "快捷键",
addTab: "添加制表符(Tab)",
removeTab: "移除制表符(Tab)",
aboutNotice: "注意：语法高亮功能仅用于较少内容的文本(文件内容太大会导致浏览器反应慢)",
toggle: "切换编辑器",
accesskey: "快捷键",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "正在处理中...",
fullscreen: "全屏编辑",
syntaxSelection: "--语法--",
closeTab: "关闭文件"
};
