/*
 *	Bulgarian translation
 *	Author:		Valentin Hristov
 *	Company:	SOFTKIT Bulgarian
 *	Site:		http://www.softkit-bg.com
 */
editAreaLoader.lang["bg"]={
newDocument: "нов документ",
searchButton: "търсене и замяна",
searchCommand: "търси следващия / отвори прозорец с търсачка",
search: "търсене",
replace: "замяна",
replaceCommand: "замяна / отвори прозорец с търсачка",
findNext: "намери следващия",
replaceAll: "замени всички",
regExp: "реголярни изрази",
matchCase: "чуствителен към регистъра",
notFound: "няма резултат.",
occurrenceReplaced: "замяната е осъществена.",
searchFieldEmpty: "Полето за търсене е празно",
restartSearchAtBegin: "До края на документа. Почни с началото.",
movePopup: "премести прозореца с търсачката",
fontSize: "--Размер на шрифта--",
goToLine: "премени към реда",
goToLinePrompt: "премени към номера на реда:",
undo: "отмени",
redo: "върни",
changeSmoothSelection: "включи/изключи някой от функциите за преглед (по красиво, но повече натоварва)",
highlight: "превключване на оцветяване на синтаксиса включена/изключена",
resetHighlight: "въстанови оцветяване на синтаксиса (ако не е синхронизиран с текста)",
wordWrap: "режим на пренасяне на дълги редове",
help: "за програмата",
save: "съхрани",
load: "зареди",
lineAbbr: "Стр",
charAbbr: "Стлб",
position: "Позиция",
total: "Всичко",
closePopup: "затвори прозореца",
shortcuts: "Бързи клавиши",
addTab: "добави табулация в текста",
removeTab: "премахни табулацията в текста",
aboutNotice: "Внимание: използвайте функцията оцветяване на синтаксиса само за малки текстове",
toggle: "Превключи редактор",
accesskey: "Бърз клавиш",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Зареждане...",
fullscreen: "на цял екран",
syntaxSelection: "--Синтаксис--",
closeTab: "Затвори файла"
};
