editAreaLoader.lang["sk"]={
newDocument: "nový prázdy dokument",
searchButton: "vyhľadaj a nahraď",
searchCommand: "hľadaj ďalsšie / otvor vyhľadávacie pole",
search: "hľadaj",
replace: "nahraď",
replaceCommand: "nahraď / otvor vyhľadávacie pole",
findNext: "nájdi ďalšie",
replaceAll: "nahraď všetko",
regExp: "platné výrazy",
matchCase: "zhodujúce sa výrazy",
notFound: "nenájdené.",
occurrenceReplaced: "výskyty nahradené.",
searchFieldEmpty: "Pole vyhľadávanie je prádzne",
restartSearchAtBegin: "End of area reached. Restart at begin.",
movePopup: "presuň vyhľadávacie okno",
fontSize: "--Veľkosť textu--",
goToLine: "prejdi na riadok",
goToLinePrompt: "prejdi na riadok:",
undo: "krok späť",
redo: "prepracovať",
changeSmoothSelection: "povoliť/zamietnúť niektoré zo zobrazených funkcií (účelnejšie zobrazenie vyžaduje  väčšie zaťaženie procesora CPU)",
highlight: "prepnúť zvýrazňovanie syntaxe zap/vyp",
resetHighlight: "zrušiť zvýrazňovanie (ak je nesynchronizované s textom)",
wordWrap: "toggle word wrapping mode",
help: "o programe",
save: "uložiť",
load: "načítať",
lineAbbr: "Ln",
charAbbr: "Ch",
position: "Pozícia",
total: "Spolu",
closePopup: "zavrieť okno",
shortcuts: "Skratky",
addTab: "pridať tabulovanie textu",
removeTab: "odstrániť tabulovanie textu",
aboutNotice: "Upozornenie: funkcia zvýrazňovania syntaxe je dostupná iba pre malý text",
toggle: "Prepnúť editor",
accesskey: "Accesskey",
tab: "Záložka",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Spracúvam...",
fullscreen: "cel=a obrazovka",
syntaxSelection: "--Vyber Syntax--",
closeTab: "Close file"
};
