editAreaLoader.lang["ru"]={
newDocument: "новый пустой документ",
searchButton: "поиск и замена",
searchCommand: "искать следующий / открыть панель поиска",
search: "поиск",
replace: "замена",
replaceCommand: "заменить / открыть панель поиска",
findNext: "найти следующее",
replaceAll: "заменить все",
regExp: "регулярное выражение",
matchCase: "учитывать регистр",
notFound: "не найдено.",
occurrenceReplaced: "вхождение заменено.",
searchFieldEmpty: "Поле поиска пустое",
restartSearchAtBegin: "Достигнут конец документа. Начинаю с начала.",
movePopup: "переместить окно поиска",
fontSize: "--Размер шрифта--",
goToLine: "перейти к строке",
goToLinePrompt: "перейти к строке номер:",
undo: "отменить",
redo: "вернуть",
changeSmoothSelection: "включить/отключить некоторые функции просмотра (более красиво, но больше использует процессор)",
highlight: "переключить подсветку синтаксиса включена/выключена",
resetHighlight: "восстановить подсветку (если разсинхронизирована от текста)",
wordWrap: "toggle word wrapping mode",
help: "о программе",
save: "сохранить",
load: "загрузить",
lineAbbr: "Стр",
charAbbr: "Стлб",
position: "Позиция",
total: "Всего",
closePopup: "закрыть всплывающее окно",
shortcuts: "Горячие клавиши",
addTab: "добавить табуляцию в текст",
removeTab: "убрать табуляцию из текста",
aboutNotice: "Внимание: функция подсветки синтаксиса только для небольших текстов",
toggle: "Переключить редактор",
accesskey: "Горячая клавиша",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Обработка...",
fullscreen: "полный экран",
syntaxSelection: "--Синтакс--",
closeTab: "Закрыть файл"
};
