editAreaLoader.lang["cs"]={
newDocument: "Nový dokument",
searchButton: "Najdi a nahraď",
searchCommand: "Hledej další / otevři vyhledávací pole",
search: "Hledej",
replace: "Nahraď",
replaceCommand: "Nahraď / otevři vyhledávací pole",
findNext: "Najdi další",
replaceAll: "Nahraď vše",
regExp: "platné výrazy",
matchCase: "vyhodnocené výrazy",
notFound: "nenalezené.",
occurrenceReplaced: "výskyty nahrazené.",
searchFieldEmpty: "Pole vyhledávání je prázdné",
restartSearchAtBegin: "Dosažen konec souboru, začínám od začátku.",
movePopup: "Přesuň vyhledávací okno",
fontSize: "--Velikost textu--",
goToLine: "Přejdi na řádek",
goToLinePrompt: "Přejdi na řádek:",
undo: "krok zpět",
redo: "znovu",
changeSmoothSelection: "Povolit nebo zakázat některé ze zobrazených funkcí (účelnější zobrazení požaduje větší zatížení procesoru)",
highlight: "Zvýrazňování syntaxe zap./vyp.",
resetHighlight: "Obnovit zvýraznění (v případě nesrovnalostí)",
wordWrap: "toggle word wrapping mode",
help: "O programu",
save: "Uložit",
load: "Otevřít",
lineAbbr: "Ř.",
charAbbr: "S.",
position: "Pozice",
total: "Celkem",
closePopup: "Zavřít okno",
shortcuts: "Zkratky",
addTab: "Přidat tabulování textu",
removeTab: "Odtsranit tabulování textu",
aboutNotice: "Upozornění! Funkce zvýrazňování textu je k dispozici pouze pro malý text",
toggle: "Přepnout editor",
accesskey: "Přístupová klávesa",
tab: "Záložka",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Zpracovávám ...",
fullscreen: "Celá obrazovka",
syntaxSelection: "--vyber zvýrazňovač--",
closeTab: "Close file"
};
