editAreaLoader.lang["en"]={
newDocument: "new empty document",
searchButton: "search and replace",
searchCommand: "search next / open search area",
search: "search",
replace: "replace",
replaceCommand: "replace / open search area",
findNext: "find next",
replaceAll: "replace all",
regExp: "regular expressions",
matchCase: "match case",
notFound: "not found.",
occurrenceReplaced: "occurences replaced.",
searchFieldEmpty: "Search field empty",
restartSearchAtBegin: "End of area reached. Restart at begin.",
movePopup: "move search popup",
fontSize: "--Font size--",
goToLine: "go to line",
goToLinePrompt: "go to line number:",
undo: "undo",
redo: "redo",
changeSmoothSelection: "enable/disable some display features (smarter display but more CPU charge)",
highlight: "toggle syntax highlight on/off",
resetHighlight: "reset highlight (if desyncronized from text)",
wordWrap: "toggle word wrapping mode",
help: "about",
save: "save",
load: "load",
lineAbbr: "Ln",
charAbbr: "Ch",
position: "Position",
total: "Total",
closePopup: "close popup",
shortcuts: "Shortcuts",
addTab: "add tabulation to text",
removeTab: "remove tabulation to text",
aboutNotice: "Notice: syntax highlight function is only for small text",
toggle: "Toggle editor",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Processing...",
fullscreen: "fullscreen",
syntaxSelection: "--Syntax--",
closeTab: "Close file"
};
