editAreaLoader.lang["it"]={
newDocument: "nuovo documento vuoto",
searchButton: "cerca e sostituisci",
searchCommand: "trova successivo / apri finestra di ricerca",
search: "cerca",
replace: "sostituisci",
replaceCommand: "sostituisci / apri finestra di ricerca",
findNext: "trova successivo",
replaceAll: "sostituisci tutti",
regExp: "espressioni regolari",
matchCase: "confronta maiuscole/minuscole<br />",
notFound: "non trovato.",
occurrenceReplaced: "occorrenze sostituite.",
searchFieldEmpty: "Campo ricerca vuoto",
restartSearchAtBegin: "Fine del testo raggiunta. Ricomincio dall'inizio.",
movePopup: "sposta popup di ricerca",
fontSize: "-- Dimensione --",
goToLine: "vai alla linea",
goToLinePrompt: "vai alla linea numero:",
undo: "annulla",
redo: "ripeti",
changeSmoothSelection: "abilita/disabilita alcune caratteristiche della visualizzazione",
highlight: "abilita/disabilita colorazione della sintassi",
resetHighlight: "aggiorna colorazione (se non sincronizzata)",
wordWrap: "toggle word wrapping mode",
help: "informazioni su...",
save: "salva",
load: "carica",
lineAbbr: "Ln",
charAbbr: "Ch",
position: "Posizione",
total: "Totale",
closePopup: "chiudi popup",
shortcuts: "Scorciatoie",
addTab: "aggiungi tabulazione",
removeTab: "rimuovi tabulazione",
aboutNotice: "Avviso: la colorazione della sintassi vale solo con testo piccolo",
toggle: "Abilita/disabilita editor",
accesskey: "Accesskey",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "In corso...",
fullscreen: "fullscreen",
syntaxSelection: "--Syntax--",
closeTab: "Close file"
};
